Added more failure tests

diff --git a/data/app_container/paas/build-application b/data/app_container/paas/build-application
--- a/data/app_container/paas/build-application
+++ b/data/app_container/paas/build-application
@@ -6,17 +6,17 @@ DEFAULT_NODE="v0.10.18"
 
 
 function log() {
-        DATE=`date '+%Y-%m-%d %H:%M:%S'`
-        printf "    ${DATE}"
-        printf '|%s' "${MODULE}" "$@"
-        printf "\n"
+    DATE=`date '+%Y-%m-%d %H:%M:%S'`
+    printf "    ${DATE}"
+    printf '|%s' "${MODULE}" "$@"
+    printf "\n"
 }
 function assert() {
-        CODE=$?
-        if [ "$CODE" != "0" ] ; then
-                log "FATAL" "$*" "code=$CODE"
-                exit $CODE
-        fi
+    CODE=$?
+    if [ "$CODE" != "0" ] ; then
+        log "FATAL" "$*" "code=$CODE"
+        exit $CODE
+    fi
 }
 
 log "INFO" "Version=${VERSION}"
@@ -25,8 +25,8 @@ cd /app
 assert "cd /app"
 
 if [ ! -r "Procfile" ] ; then
-	log "ERROR" "file=Procfile" "msg=Not found"
-	exit -1
+    log "ERROR" "file=Procfile" "msg=Not found"
+    exit -1
 fi
 
 WEB=`grep web Procfile | cut -f2-99 -d:`
@@ -37,70 +37,70 @@ assert "extracting the Command to strart the application"
 log "INFO" "Command=$CMD"
 
 if [ "$CMD" == "node" -o "$CMD" == "forever" -o "$CMD" == "pm2" ] ; then
-	log "INFO" "Building node.js application container"
-        NODE=`grep "\"node\" *:" package.json | cut -f4 -d\"`
-        . /.nvm/nvm.sh
-        if [ "$NODE" == "0.8.x" ] ; then
-                NODE="v0.8.25"
-        fi
-        if [ "$NODE" == "" -o "$NODE" == "0.10.x" -o "$NODE" == "latest" -o "$NODE" == "*" ] ; then
-                NODE=$DEFAULT_NODE
-        fi
-	log "INFO" "Installing node version $NODE"
+    log "INFO" "Building node.js application container"
+    NODE=`grep "\"node\" *:" package.json | cut -f4 -d\"`
+    . /.nvm/nvm.sh
+    if [ "$NODE" == "0.8.x" ] ; then
+        NODE="v0.8.25"
+    fi
+    if [ "$NODE" == "" -o "$NODE" == "0.10.x" -o "$NODE" == "latest" -o "$NODE" == "*" ] ; then
+        NODE=$DEFAULT_NODE
+    fi
+    log "INFO" "Installing node version $NODE"
+    nvm install $NODE 2>&1 | sed -e 's/^/        /'
+    if [ $? != 0 ] ; then
+        log "WARN" "Unable to install node.js version=$NODE"
+        NODE=$DEFAULT_NODE
         nvm install $NODE 2>&1 | sed -e 's/^/        /'
-	if [ $? != 0 ] ; then
-		log "WARN" "Unable to install node.js version=$NODE"
-		NODE=$DEFAULT_NODE
-        	nvm install $NODE 2>&1 | sed -e 's/^/        /'
-		assert "nvm install $NODE"
-	fi
-	if [ "$CMD" == "forever" -o "$CMD" == "pm2" ] ; then
-		log "INFO" "Installing $CMD"
-		npm install -g $CMD 2>&1 | sed -e 's/^/        /'
-		if [ $? != 0 ] ; then
-			log "WARN" "Unable to install '$CMD', defaulting to 'node' instead"
-			CMD="node"
-		fi
-	fi
-	log "INFO" "Installing npm modules"
-        npm install 2>&1 | sed -e 's/^/        /'
-	assert "npm install"
+        assert "nvm install $NODE"
+    fi
+    if [ "$CMD" == "forever" -o "$CMD" == "pm2" ] ; then
+        log "INFO" "Installing $CMD"
+        npm install -g $CMD 2>&1 | sed -e 's/^/        /'
+        if [ $? != 0 ] ; then
+            log "WARN" "Unable to install '$CMD', defaulting to 'node' instead"
+            CMD="node"
+        fi
+    fi
+    log "INFO" "Installing npm modules"
+    npm install 2>&1 | sed -e 's/^/        /'
+    assert "npm install"
 
-	log "INFO" "Creating application startup script ./.paas-start-cmd"
-	cat > ./.paas-start-cmd << EOF_NODE
+    log "INFO" "Creating application startup script ./.paas-start-cmd"
+    cat > ./.paas-start-cmd << EOF_NODE
 #/bin/bash
 . /.nvm/nvm.sh
 nvm use ${NODE}
 cd /app
 $WEB
 EOF_NODE
-        chmod a+x ./.paas-start-cmd 2>&1 | sed -e 's/^/        /'
-	assert "chmod a+x ./.paas-start-cmd"
+    chmod a+x ./.paas-start-cmd 2>&1 | sed -e 's/^/        /'
+    assert "chmod a+x ./.paas-start-cmd"
 else
-	if [ "$CMD" == "java" ] ; then
-		log "INFO" "Building java application container"
+    if [ "$CMD" == "java" ] ; then
+        log "INFO" "Building java application container"
 
-		export JAVA_HOME="/usr/lib/jvm/$JDK"
-		export PATH="$JAVA_HOME/bin:${PATH}"
+        export JAVA_HOME="/usr/lib/jvm/$JDK"
+        export PATH="$JAVA_HOME/bin:${PATH}"
 
-		log "INFO" "Building java application"
-		log "INFO" "JAVA_HOME=$JAVA_HOME"
-		log "INFO" "PATH=$PATH"
-		mvn -Dmaven.test.skip=true -Dmaven.javadoc.skip=true -Dsource.skip=true clean package  2>&1 | sed -e 's/^/        /'
-		assert "mvn -Dmaven.test.skip=true -Dmaven.javadoc.skip=true -Dsource.skip=true clean package"
+        log "INFO" "Building java application"
+        log "INFO" "JAVA_HOME=$JAVA_HOME"
+        log "INFO" "PATH=$PATH"
+        mvn -Dmaven.test.skip=true -Dmaven.javadoc.skip=true -Dsource.skip=true clean package  2>&1 | sed -e 's/^/        /'
+        assert "mvn -Dmaven.test.skip=true -Dmaven.javadoc.skip=true -Dsource.skip=true clean package"
 
-		cat > ./.paas-start-cmd << EOF_JAVA
+        cat > ./.paas-start-cmd << EOF_JAVA
 #/bin/bash" > ./.paas-start-cmd
 export JAVA_HOME=/usr/lib/jvm/$JDK
 export PATH=$JAVA_HOME/bin:\${PATH}
 cd /app
 $WEB
 EOF_JAVA
-		chmod a+x ./.paas-start-cmd 2>&1 | sed -e 's/^/        /'
-		assert "chmod a+x ./.paas-start-cmd"
-	else
-		log "FATAL" "Unknown language '$CMD'"
-		exit -2
-	fi
+        chmod a+x ./.paas-start-cmd 2>&1 | sed -e 's/^/        /'
+        assert "chmod a+x ./.paas-start-cmd"
+    else
+        log "FATAL" "Unknown language '$CMD'"
+        exit -2
+    fi
 fi
 log "INFO" "SUCCESS"
diff --git a/data/bin/uploadkeyd b/data/bin/uploadkeyd
--- a/data/bin/uploadkeyd
+++ b/data/bin/uploadkeyd
@@ -22,6 +22,10 @@ while [ 1 ] ; do
     rm -f /tmp/add-key.sock
     assert "rm -f /tmp/add-key.sock"
     sudo -u git /bin/bash -c "umask 000 ; nc -l -U /tmp/add-key.sock | /home/git/bin/git-add-authorization"
-    log "INFO" "adding key to git account"
+    if [ $? != 0 ] ; then
+        log "ERROR" "Unable to send key to be added"
+    else
+        log "INFO" "adding key to git account"
+    fi
 done
 
diff --git a/data/git/bin/run-app-container b/data/git/bin/run-app-container
--- a/data/git/bin/run-app-container
+++ b/data/git/bin/run-app-container
@@ -26,37 +26,57 @@ if [[ ! -f "$HOME/$APP/CONTAINER" ]]; then
 	# does the application REQUIRE a special port
 	if [[ -f "$HOME/$APP/PORT" ]]; then
 		PORT=`cat "$HOME/$APP/PORT"`
+		assert "Restauring application $APP internal port: $PORT"
 	fi
 
 	log "INFO" "Starting application $CONTAINER" "PORT=$PORT"
 	ID=$(docker run -d -p $PORT -e PORT=$PORT $CONTAINER /bin/bash -c "/app/.paas-start-cmd")
+	assert "Staring application $APP in container $ID"
 	echo $ID > "$HOME/$APP/CONTAINER"
 	NGINXPORT=$(docker port $ID $PORT)
+	assert "Extracting public port for application $APP"
 	log "INFO" "Application $CONTAINER" "ID=$ID" "NGINX PORT=$NGINXPORT"
 	if [[ ! -f "$HOME/$APP/PORT" ]] ; then
 		echo $PORT > "$HOME/$APP/PORT"
+		assert "Saving private port for application $APP"
 	fi
 	echo $NGINXPORT > "$HOME/$APP/NGINXPORT"
+	assert "Saving Public port for application $APP"
 
 	HOSTNAME="${APP/\//-}.$(< "$HOME/DOMAIN")"
+	assert "Building application URL"
 	$HOME/bin/nginx-app-conf ${APP/\//-} $NGINXPORT $HOSTNAME > $HOME/$APP/nginx.conf
+	assert "Writing NGINX configuration file"
 	nc -U /tmp/nginx-reload.sock
 	assert "nc -U /tmp/nginx-reload.sock"
 	log "INFO" "Signaling NGINX to reload the configuration" "${APP/\//-}" "$NGINXPORT" "$HOSTNAME"
 	echo $HOSTNAME > "$HOME/$APP/HOSTNAME"
+	assert "Saving application hostname"
 	sleep 10
+	assert "sleep 10"
 	docker logs $ID 2>&1 | sed -e 's/^/        /'
+	assert "Extracting application logs"
 else
 	# Redeployment 
 	OLDID=$(< "$HOME/$APP/CONTAINER")
+	assert "Extracting application container ID:$ID"
 	log "INFO" "Terminating the running container" "ID=$OLDID"
 	docker kill $OLDID > /dev/null
+	if [ $? != 0 ] ; then
+		log "WARN" "Failed to kill the running container: $?"
+	fi
 	PORT=$(< "$HOME/$APP/PORT")
+	assert "Restoring private port"
 	NGINXPORT=$(< "$HOME/$APP/NGINXPORT")
+	assert "Restoring public port"
 	ID=$(docker run -d -p "$NGINXPORT:$PORT" -e "PORT=$PORT" $CONTAINER /bin/bash -c "/app/.paas-start-cmd")
+	assert "Running application $APP on public port $NGINXPORT, private port $PORT, container $CONTAINER"
 	echo $ID > "$HOME/$APP/CONTAINER"
+	assert "Saving running application container"
 	log "INFO" "Starting application $CONTAINER" "PORT=$PORT" "NGINXPORT=$NGINXPORT" "ID=$ID"
 	sleep 10
+	assert "sleep 10"
 	docker logs $ID 2>&1 | sed -e 's/^/        /'
+	assert "Extracting log of running container application $APP"
 fi
 log "INFO" "SUCCESS"
